structure(list(url = "https://ec2.usersnap.com/angular/apikeys/R/reports?includeapikey=false&offset=0&limit=-1&search=%5B%7B%22type%22%3A%22state%22%2C%22id%22%3A%22open%22%7D%5D",
    status_code = 500L, headers = structure(list(server = "nginx",
        date = "Sat, 24 Jun 2017 03:29:07 GMT", `content-type` = "text/html; charset=utf-8",
        `content-length` = "813", connection = "keep-alive",
        pragma = "no-cache", `cache-control` = "no-cache", `access-control-allow-methods` = "GET, POST, UPDATE, DELETE, OPTIONS",
        `access-control-allow-headers` = "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type",
        `access-control-allow-credentials` = "true", `access-control-expose-headers` = "Total-Count,Total-Unread-Count"), .Names = c("server",
    "date", "content-type", "content-length", "connection", "pragma",
    "cache-control", "access-control-allow-methods", "access-control-allow-headers",
    "access-control-allow-credentials", "access-control-expose-headers"
    ), class = c("insensitive", "list")), all_headers = list(
        structure(list(status = 500L, version = "HTTP/1.1", headers = structure(list(
            server = "nginx", date = "Sat, 24 Jun 2017 03:29:07 GMT",
            `content-type` = "text/html; charset=utf-8", `content-length` = "813",
            connection = "keep-alive", pragma = "no-cache", `cache-control` = "no-cache",
            `access-control-allow-methods` = "GET, POST, UPDATE, DELETE, OPTIONS",
            `access-control-allow-headers` = "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type",
            `access-control-allow-credentials` = "true", `access-control-expose-headers` = "Total-Count,Total-Unread-Count"), .Names = c("server",
        "date", "content-type", "content-length", "connection",
        "pragma", "cache-control", "access-control-allow-methods",
        "access-control-allow-headers", "access-control-allow-credentials",
        "access-control-expose-headers"), class = c("insensitive",
        "list"))), .Names = c("status", "version", "headers"))),
    cookies = structure(list(domain = logical(0), flag = logical(0),
        path = logical(0), secure = logical(0), expiration = structure(numeric(0), class = c("POSIXct",
        "POSIXt")), name = logical(0), value = logical(0)), .Names = c("domain",
    "flag", "path", "secure", "expiration", "name", "value"), row.names = integer(0), class = "data.frame"),
    content = charToRaw("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n<head>\n <title>Server Error 500</title>\n<!-- CSS Imports -->\n<link rel=\"stylesheet\" href=\"/error/style/black.css\" type=\"text/css\" media=\"screen\" />\n\n<!-- Favorite Icons -->\n<link rel=\"icon\" href=\"/error/img/favicon.ico\" type=\"image/png\" />\n\n<style type=\"text/css\">\n        .red {\n            color:#FF0000;\n        }\n        .bold {\n            font-weight: bold;\n        }\n</style>\n</head>\n\n<body>\n    <div id=\"container\">\n        \n    <html>\n    <head>\n    <title>Server Error</title>\n    \n    </head>\n    <body>\n    <h1>Server Error</h1>\n    An internal server error occurred\n    \n    </body>\n    </html>\n    </div>\n</body>\n</html>\n"),
    date = structure(1498274947, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = structure(c(0, 3.4e-05, 3.6e-05,
    0.000104, 1.575131, 1.575182), .Names = c("redirect", "namelookup",
    "connect", "pretransfer", "starttransfer", "total")), request = structure(list(
        method = "GET", url = "https://ec2.usersnap.com/angular/apikeys/R/reports?includeapikey=false&offset=0&limit=-1&search=%5B%7B%22type%22%3A%22state%22%2C%22id%22%3A%22open%22%7D%5D",
        headers = structure("application/json, text/xml, application/xml, */*", .Names = "Accept"),
        fields = NULL, options = structure(list(useragent = "libcurl/7.51.0 r-curl/2.3 httr/1.2.1",
            cookie = "bugrep=redacted",
            httpget = TRUE), .Names = c("useragent", "cookie", 
        "httpget")), auth_token = NULL, output = structure(list(), class = c("write_memory",
        "write_function"))), .Names = c("method", "url", "headers",
    "fields", "options", "auth_token", "output"), class = "request")), .Names = c("url",
"status_code", "headers", "all_headers", "cookies", "content",
"date", "times", "request"), class = "response")
